#!/usr/bin/env bash

# Version 1.1.0

VALET_REGISTRY=${VALET_REGISTRY:="ghcr.io"}
VALET_IMAGE=${VALET_IMAGE:-"$VALET_REGISTRY/valet-customers/valet-cli"}

docker login $VALET_REGISTRY

# pulling the latest can cause weird issues because the team is moving fast
# better test with the latest tag before a bootcamp
# find the last version here: https://github.com/valet-customers/distribution/pkgs/container/valet-cli

# docker pull $VALET_IMAGE:latest
docker pull $VALET_IMAGE:0.1.0.10368 # <-- version from 20211005